### ISSUE TITLE
P220 peek function does not pass the test

### ISSUE THREAD

**Issue by quanhewan** [teropa/build-your-own-angularjs#245]
on bottom of the page 220, the peek function below does not pass the spec test (actually it ruined the whole functionality of peek and expect):
```javascript
if (text === e1 || text === e2 || text === e3 || text === e4 ||
    (!e1 && !e2 && !e3 && !e4)) 
    {return this.tokens[0];}
```

I changed it to
```javascript
if ((!e1 && !e2 && !e3 && !e4)|| (e1 && text === e1) ||(e2 && text === e2) ||
            (e3 && text === e3)||(e4 && text === e4))
             {return this.tokens[0];}
```
and it passed.

I am kind of new to Javascript and AngularJS so cannot exactly tell what the problem is, but it might be related to the checking of undefined e2-e4 when they are not available in the argument.

**Comment by Foxandxss** [comment]
I hadn't that issue in any of my revisions.

**Comment by teropa** [comment]
@quanhewan Are you running tests in a browser other than PhantomJS? Thinking if this might be a problem that crops up in a particular browser.

If there's an error you're getting, could you post it here?

**Comment by Foxandxss** [comment]
@teropa I run the tests with Chrome, I like the output windows :P. So at least with chrome it passes.

**Comment by quanhewan** [comment]
@teropa I run it in PhantomJS 1.9 under Windows 8.1.  I also tested it on Chrome and got the same error:
```
parse can parse a string in single quotes
TypeError: Cannot read property 'fn' of undefined
TypeError: Cannot read property 'fn' of undefined
    at Parser.primary (http://localhost:7357/src/parse.js:467:24)
    at Parser.unary (http://localhost:7357/src/parse.js:751:21)
    at Parser.multiplicative (http://localhost:7357/src/parse.js:773:21)
    at Parser.additive (http://localhost:7357/src/parse.js:791:21)
    at Parser.relational (http://localhost:7357/src/parse.js:800:21)
    at Parser.equality (http://localhost:7357/src/parse.js:809:21)
    at Parser.logicalAND (http://localhost:7357/src/parse.js:818:21)
    at Parser.logicalOR (http://localhost:7357/src/parse.js:827:21)
    at Parser.ternary (http://localhost:7357/src/parse.js:836:21)
    at Parser.assignment (http://localhost:7357/src/parse.js:731:21)

```
and I think the "fn" refers to the token comes from the expect function;
(at Parser.primary (http://localhost:7357/src/parse.js:467:24))
```
        var token = this.expect();
        primary = token.fn;
```

Hope this helps...  Thanks.

**Comment by teropa** [comment]
Closing this as the parser has been rewritten. No token will have an `fn` attribute anymore.
