### ISSUE TITLE
P 232 / Method Calls: Test about fn calls with multiple arguments fails

### ISSUE THREAD

**Issue by cobalamin** [teropa/build-your-own-angularjs#293]
I have no idea why this happens in Chrome connected to the testem server, but not in PhantomJS. But here goes:

The code `var args = _.map(ast.args, _.bind(this.recurse, this));` - from page 232 - makes for a problem where the newly introduced `ctx` (in the book itself called `context`) parameter of `this.recurse` is bound to an array index, because of the style of the [_.map iterator function](https://lodash.com/docs#map): `(value, index|key, collection)`. The line:
`ctx.context = localsHasProperty + ' ?l:s';`
then fails with an error because it essentially tries to change the `context` property of the number `1`:

    parse functions parses a function call with multiple arguments
      ✘ TypeError: Cannot assign to read only property 'context' of 1
      at ASTCompiler.recurse (http://localhost:7357/src/parse.js:366:21)
      at wrapper (http://localhost:7357/node_modules/lodash/index.js:3095:19)
      at arrayMap (http://localhost:7357/node_modules/lodash/index.js:1406:25)
      at Function.map (http://localhost:7357/node_modules/lodash/index.js:6710:14
      )
      at ASTCompiler.recurse (http://localhost:7357/src/parse.js:403:20)
      at ASTCompiler.recurse (http://localhost:7357/src/parse.js:336:44)
      at ASTCompiler.compile (http://localhost:7357/src/parse.js:321:8)
      at Parser.parse (http://localhost:7357/src/parse.js:468:27)
      at parse (http://localhost:7357/src/parse.js:475:19)
      at Object.<anonymous> (http://localhost:7357/test/parse_spec.js:1:7626)

See https://github.com/cobalamin/myangular/commit/5b7237d544b3871ae0f153325834144a20ced3f0 for the change I made to fix this: Just define another inline function that only passes the arg parameter, not the index. (Also, use _.map's own this binding mechanism as the third parameter, as it's more terse).
In the code of this repo, this style is already used, but it's not listed like this in the book.

**Comment by Foxandxss** [comment]
And that is why I always test in Chrome as well.

I also got into that issue and it drove myself crazy. That fixed it. Thanks.

**Comment by teropa** [comment]
Right, because of the additional arguments `_.map` passes to the iterator, there may be problems when applied directly to functions that use those argument positions for something else (such as `recurse`).

Fixed, thanks!
